# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('secondname', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('starting_balance', models.IntegerField(default=0, verbose_name='Начальный баланс')),
                ('type', models.CharField(choices=[('SUM', 'SUM'), ('$', 'USD')], default='(SUM)', max_length=3)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pouches', models.ManyToManyField(to='lib.Pouch')),
            ],
        ),
    ]
