# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 11:21
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20171024_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#F0F0F0', max_length=18),
        ),
    ]
