# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouch',
            name='type',
            field=models.CharField(choices=[('SUM', 'SUM'), ('$', 'USD')], default='SUM', max_length=3),
        ),
    ]
