# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-10 09:15
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20171204_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
