# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0021_auto_20181024_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_date', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(default='1', max_length=2)),
                ('request_result', models.CharField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='0', max_length=9, unique=True)),
                ('ref_key', models.CharField(max_length=50, unique=True)),
                ('ops_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(default='1', max_length=2)),
                ('request_work', models.CharField(default='нет описания', max_length=100)),
                ('request_address', models.CharField(default='q-b-a', max_length=50)),
                ('request_comment', models.CharField(blank=True, max_length=255)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='logging',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SubscriberRequest'),
        ),
    ]
