# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberrequest',
            name='subs_add_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriberrequest',
            name='subs_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
