# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0002_auto_20170914_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTransactionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('outcome', models.IntegerField(default=0)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTransactionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('outcome', models.IntegerField(default=0)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTransactionPouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('outcome', models.IntegerField(default=0)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Pouch')),
            ],
        ),
    ]
