# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_balancestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancestamp',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='balancestamp',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
