# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20170925_1233'),
        ('report', '0004_auto_20171025_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancestamp',
            old_name='balance',
            new_name='balance_after',
        ),
        migrations.AddField(
            model_name='balancestamp',
            name='balance_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancestamp',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calc.Transaction'),
        ),
        migrations.AddField(
            model_name='balancestamp',
            name='transaction_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.TransactionChangeHistory'),
        ),
    ]
