# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20171026_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancestamp',
            name='sum_val',
            field=models.IntegerField(default=0),
        ),
    ]
