# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_balancestamp_sum_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancestamp',
            name='reason',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
