# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('secondname', models.CharField(max_length=30, null=True)),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('telephone', models.BigIntegerField(unique=True)),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
    ]
