# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20170914_1615'),
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Staff')),
            ],
        ),
    ]
