# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_accept',
            field=models.DateTimeField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_close',
            field=models.DateTimeField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Staff'),
        ),
    ]
