# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0004_auto_20170914_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_accept',
            field=models.DateTimeField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_close',
            field=models.DateTimeField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
    ]
