# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_auto_20170914_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Staff'),
        ),
    ]
