# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0006_auto_20170914_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_accept',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
