# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('checking', models.BooleanField(default=True)),
                ('withholding', models.BooleanField(default=False)),
                ('responsible', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BonusWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('checking', models.BooleanField(default=True)),
                ('withholding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2017-9-1')),
                ('balance_before', models.IntegerField(default=0)),
                ('accrual', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('withholding', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('issued', models.IntegerField(default=0)),
                ('balance_now', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time_range', models.CharField(choices=[('Оклад', 'salary'), ('Процент', 'percent'), ('Месяц', 'month'), ('День', 'day'), ('Час', 'hour')], max_length=20)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Category')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lib.Person')),
                ('position', models.ManyToManyField(to='salary.WorkCalc')),
            ],
        ),
        migrations.AddField(
            model_name='total',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.Worker'),
        ),
        migrations.AddField(
            model_name='bonuswork',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.WorkCalc'),
        ),
        migrations.AddField(
            model_name='bonuswork',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.Worker'),
        ),
        migrations.AddField(
            model_name='accountchange',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.CategoryOfChange'),
        ),
        migrations.AddField(
            model_name='accountchange',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='total',
            unique_together=set([('date', 'worker')]),
        ),
    ]
