# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20170925_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Час', 'hour'), ('Оклад', 'salary'), ('Процент', 'percent'), ('День', 'day'), ('Месяц', 'month')], max_length=20),
        ),
    ]
