# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20170925_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 1, 16, 21, 35, 581325)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('День', 'day'), ('Оклад', 'salary'), ('Процент', 'percent'), ('Час', 'hour'), ('Месяц', 'month')], max_length=20),
        ),
    ]
