# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 17:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0007_auto_20180515_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 1, 17, 42, 4, 517780)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Месяц', 'month'), ('Процент', 'percent'), ('Час', 'hour'), ('Оклад', 'salary'), ('День', 'day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='coworker',
            field=models.ManyToManyField(blank=True, to='salary.Worker', verbose_name='Помощники'),
        ),
    ]
