# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_auto_20180520_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workreport',
            options={'ordering': ['-working_date']},
        ),
        migrations.AddField(
            model_name='workreport',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарий начальника'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 1, 13, 12, 48, 548338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('День', 'day'), ('Оклад', 'salary'), ('Час', 'hour'), ('Месяц', 'month')], max_length=20),
        ),
    ]
