# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-31 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_auto_20180520_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workreport',
            options={'ordering': ['-working_date']},
        ),
        migrations.AddField(
            model_name='workreport',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарий начальника'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 1, 16, 57, 39, 227912)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Оклад', 'salary'), ('Час', 'hour'), ('Процент', 'percent'), ('Месяц', 'month'), ('День', 'day')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='workreport',
            unique_together=set([('working_date', 'work', 'quarter', 'building', 'apartment')]),
        ),
    ]
