# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_auto_20180601_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 1, 10, 38, 31, 308480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Месяц', 'month'), ('День', 'day'), ('Час', 'hour'), ('Процент', 'percent'), ('Оклад', 'salary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=1250, verbose_name='Комментарий начальника'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='comment',
            field=models.CharField(blank=True, max_length=1250, null=True, verbose_name='Комментарий'),
        ),
    ]
