# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 12:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_auto_20180602_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='can_make_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 1, 12, 0, 39, 100307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Месяц', 'month'), ('Оклад', 'salary'), ('День', 'day'), ('Час', 'hour')], max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарий начальника'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
