# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-11 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_auto_20180704_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workreport',
            name='stored',
            field=models.BooleanField(default=False, verbose_name='Отложен'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='tagged_coworker',
            field=models.BooleanField(default=False, verbose_name='Отмечен помощник'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 1, 12, 0, 23, 140830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Час', 'hour'), ('Месяц', 'month'), ('Оклад', 'salary'), ('День', 'day')], max_length=20),
        ),
    ]
