# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-01 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_auto_20180718_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 5, 37, 23, 399372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('День', 'day'), ('Процент', 'percent'), ('Месяц', 'month'), ('Час', 'hour'), ('Оклад', 'salary')], max_length=20),
        ),
    ]
