# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-08 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_auto_20180801_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 12, 19, 15, 593488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Месяц', 'month'), ('День', 'day'), ('Оклад', 'salary'), ('Час', 'hour')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий начальника'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='apartment',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кв-ра'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='hours_qty',
            field=models.SmallIntegerField(default=1, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='quarter',
            field=models.SmallIntegerField(verbose_name='Кв-л'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='working_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
