# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-10 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0016_auto_20180808_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='income',
            field=models.IntegerField(default=None, null=True, verbose_name='Принятые кредиты'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 12, 19, 25, 955811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='cost',
            field=models.IntegerField(default=None, null=True, verbose_name='Стоимость'),
        ),
    ]
