# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-10 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_auto_20180910_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 12, 46, 20, 322734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Оклад', 'salary'), ('Месяц', 'month'), ('Час', 'hour'), ('Процент', 'percent'), ('День', 'day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='income',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Принятые кредиты'),
        ),
    ]
