# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-18 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20180801_1011'),
        ('salary', '0018_auto_20180910_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='coworkers_qt_ty',
            field=models.SmallIntegerField(default=1, verbose_name='Кол-во подтвержденных'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Transaction', verbose_name='Связанная транзакция'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 12, 48, 11, 674519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Месяц', 'month'), ('День', 'day'), ('Процент', 'percent'), ('Оклад', 'salary'), ('Час', 'hour')], max_length=20),
        ),
    ]
