# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-10 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_auto_20181010_1415'),
        ('salary', '0019_auto_20180918_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 9, 15, 29, 60079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Оклад', 'salary'), ('Месяц', 'month'), ('День', 'day'), ('Час', 'hour')], max_length=20),
        ),
    ]
