# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-24 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0020_auto_20181010_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 8, 13, 24, 66708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Оклад', 'salary'), ('Час', 'hour'), ('День', 'day'), ('Месяц', 'month')], max_length=20),
        ),
    ]
