# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-24 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0021_auto_20181024_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='one_c_work_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='one_c_worker_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 11, 6, 41, 952495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='time_range',
            field=models.CharField(choices=[('Процент', 'percent'), ('Час', 'hour'), ('Месяц', 'month'), ('Оклад', 'salary'), ('День', 'day')], max_length=20),
        ),
    ]
