# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableTvCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CableTvDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CableTvPouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvCat')),
            ],
        ),
        migrations.CreateModel(
            name='CableTvQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CableTvResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='2017', max_length=5)),
                ('date_month', models.CharField(choices=[('Январь', 'Jan'), ('Февраль', 'Feb'), ('Март', 'March'), ('Апрель', 'Apr'), ('Май', 'May'), ('Июнь', 'June'), ('Июль', 'July'), ('Август', 'Aug'), ('Сентябрь', 'Sept'), ('Октябрь', 'Oct'), ('Ноябрь', 'Nov'), ('Декабрь', 'Dec')], max_length=15)),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('check', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvPouch')),
            ],
        ),
        migrations.CreateModel(
            name='CableTvSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CableTvType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CableTvZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvDistrict')),
                ('quarter', models.ManyToManyField(to='cabletv.CableTvQuarter')),
            ],
        ),
        migrations.AddField(
            model_name='cabletvcat',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvSource', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cabletvcat',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvType'),
        ),
        migrations.AddField(
            model_name='cabletvcat',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabletv.CableTvZone'),
        ),
        migrations.AlterUniqueTogether(
            name='cabletvresult',
            unique_together=set([('date_year', 'date_month', 'account')]),
        ),
    ]
