# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время проведения')),
                ('sum_val', models.IntegerField(verbose_name='Cумма')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='Комментарий')),
                ('typeof', models.BooleanField(default=False, verbose_name='Пополнение')),
                ('checking', models.BooleanField(default=True, verbose_name='Проведено')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания/изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib.Category', verbose_name='Категория')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Pouch', verbose_name='Счет')),
                ('who_is', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib.Person', verbose_name='На кого')),
            ],
        ),
    ]
