# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20170914_1615'),
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('date', 'sum_val', 'category', 'who_is', 'comment', 'money', 'typeof')]),
        ),
    ]
