# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-10 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20180801_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
